cvmfs_config_repo:
  domain: galaxyproject.org
  key:
    path: /etc/cvmfs/keys/galaxyproject.org/cvmfs-config.galaxyproject.org.pub
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuJZTWTY3/dBfspFKifv8
      TWuuT2Zzoo1cAskKpKu5gsUAyDFbZfYBEy91qbLPC3TuUm2zdPNsjCQbbq1Liufk
      uNPZJ8Ubn5PR6kndwrdD13NVHZpXVml1+ooTSF5CL3x/KUkYiyRz94sAr9trVoSx
      THW2buV7ADUYivX7ofCvBu5T6YngbPZNIxDB4mh7cEal/UDtxV683A/5RL4wIYvt
      S5SVemmu6Yb8GkGwLGmMVLYXutuaHdMFyKzWm+qFlG5JRz4okUWERvtJ2QAJPOzL
      mAG1ceyBFowj/r3iJTa+Jcif2uAmZxg+cHkZG5KzATykF82UH1ojUzREMMDcPJi2
      dQIDAQAB
      -----END PUBLIC KEY-----
  urls:
    - http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@
    - http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@
    - http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@
    - http://cvmfs1-ufr0.galaxyproject.eu/cvmfs/@fqrn@
    - http://cvmfs1-mel0.gvl.org.au/cvmfs/@fqrn@
  repository:
    repository: cvmfs-config.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: "root"
    server_options: []
    client_options: []

cvmfs_keys:
  - path: /etc/cvmfs/keys/galaxyproject.org/cvmfs-config.galaxyproject.org.pub
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuJZTWTY3/dBfspFKifv8
      TWuuT2Zzoo1cAskKpKu5gsUAyDFbZfYBEy91qbLPC3TuUm2zdPNsjCQbbq1Liufk
      uNPZJ8Ubn5PR6kndwrdD13NVHZpXVml1+ooTSF5CL3x/KUkYiyRz94sAr9trVoSx
      THW2buV7ADUYivX7ofCvBu5T6YngbPZNIxDB4mh7cEal/UDtxV683A/5RL4wIYvt
      S5SVemmu6Yb8GkGwLGmMVLYXutuaHdMFyKzWm+qFlG5JRz4okUWERvtJ2QAJPOzL
      mAG1ceyBFowj/r3iJTa+Jcif2uAmZxg+cHkZG5KzATykF82UH1ojUzREMMDcPJi2
      dQIDAQAB
      -----END PUBLIC KEY-----

rabbitmq_port: "5672"
rabbitmq_management_port: "15672"
rabbitmq_admin_username: admin
rabbitmq_admin_password: admin
rabbitmq_galaxy_vhost: galaxy
rabbitmq_galaxy_username: galaxy
rabbitmq_galaxy_password: galaxy
rabbitmq_flower_username: flower
rabbitmq_flower_password: flower
