- hosts: localhost
  connection: local
  remote_user: root
  vars:
    docker_install_compose: false
    docker_install_compose_plugin: false
    docker_users:
      - "{{ galaxy_user_name }}"
    docker_service_manage: false
  roles:
    - role: geerlingguy.docker
  tasks:
    - name: Purge systemd and perform cleanup
      shell: apt purge -y systemd && apt-get autoremove -y && apt-get clean
