- hosts: localhost
  connection: local
  remote_user: root
  vars:
    flower_python_package_version: 1.2.0
    flower_custom_logging: false
    flower_user: galaxy
    flower_group: galaxy
    flower_venv_user: galaxy
    flower_venv_group: galaxy
    flower_install: true
    flower_conf_dir: /etc/flower
    flower_bind_address: 0.0.0.0
    flower_port: 5555
    flower_broker_api: http://flower:flower@localhost:5671/api/  # URL of broker (RabbitMQ Management) API
    flower_persistent: true
    flower_proxy_prefix: /flower
    flower_ui_users: []
  roles:
      - role: galaxy-flower
  tasks:
    - name: Add url prefix to flower config
      lineinfile:
        path: "{{ flower_conf_dir }}/flowerconfig.py"
        line: 'url_prefix = "{{ flower_proxy_prefix }}"'
