- hosts: localhost
  connection: local
  remote_user: root
  vars:
    flower_python_package_version: 1.2.0
    flower_custom_logging: false
    flower_conf_dir: "{{ flower_conf_path | dirname }}"
    flower_ui_users: []
  roles:
    - role: galaxy-flower
  tasks:
    - name: Add url prefix to flower config
      lineinfile:
        path: "{{ flower_conf_path }}"
        line: 'url_prefix = "{{ flower_url_prefix }}"'
