- hosts: localhost
  connection: local
  remote_user: root
  tasks:
    - name: "Install Galaxy job conf"
      template: src=job_conf.xml.j2 dest={{ galaxy_job_conf_path }} owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

    - name: "Install Galaxy container resolution configuration"
      template: src=container_resolvers_conf.yml.j2 dest={{ galaxy_container_resolvers_conf_path }} owner={{ galaxy_user_name }} group={{ galaxy_user_name }}
      when: galaxy_container_resolution | bool
