- hosts: localhost
  connection: local
  remote_user: root
  tasks:
    - name: "Install galaxy user creation script."
      template: src=create_galaxy_user.py.j2 dest=/usr/local/bin/create_galaxy_user.py mode=a+x

    - name: "Install galaxy check database script."
      template: src=check_database.py.j2 dest=/usr/local/bin/check_database.py mode=a+x

    - name: "Install export user files script."
      template: src=export_user_files.py.j2 dest=/usr/local/bin/export_user_files.py mode=a+x

    - name: "Install add_tool_shed script."
      template: src=add_tool_shed.py.j2 dest=/usr/local/bin/add-tool-shed mode=a+x
      
    - name: "Install startup lite script."
      template: src=startup_lite.sh.j2 dest=/usr/bin/startup_lite mode=a+x

    - name: "Install cgroupfs_mount.sh for startup script."
      template: src=cgroupfs_mount.sh.j2 dest=/root/cgroupfs_mount.sh mode=a+x

    - name: "Install update_yaml_value script."
      template: src=update_yaml_value.py.j2 dest=/usr/local/bin/update_yaml_value mode=a+x
