- hosts: localhost
  connection: local
  remote_user: root
  tasks:
    - name: "Run common_startup.sh to build the galaxy client"
      shell: scripts/common_startup.sh
      environment:
        GALAXY_VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
      args:
        chdir: "{{ galaxy_server_dir }}"
      become: True
      become_user: "{{ galaxy_user_name }}"

    - name: "Install watchdog for galaxy"
      pip:
        name: "watchdog"
        virtualenv: "{{ galaxy_venv_dir }}"
        virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
        extra_args: --index-url https://wheels.galaxyproject.org/simple --extra-index-url https://pypi.python.org/simple
      become: True
      become_user: "{{ galaxy_user_name }}"

    - name: Ensure galaxy_logs dir exists
      file: path={{ galaxy_logs_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}
