- hosts: localhost
  connection: local
  remote_user: root
  vars:
    proftpd_galaxy_auth: yes
    galaxy_user:
      name: "{{ galaxy_user_name }}"
    proftpd_galaxy_modules:
      - mod_sql.c
      - mod_sql_passwd.c
      - mod_sql_postgres.c
      - mod_sftp.c
      - mod_sftp_pam.c
      - mod_sftp_sql.c
    proftpd_create_ftp_upload_dir: yes
    proftpd_options:
      - User: "{{ galaxy_user_name }}"
      - Group: "{{ galaxy_user_name }}"
    proftpd_global_options:
      - PassivePorts: "{{ proftpd_passive_port_low }} {{ proftpd_passive_port_high }}"
    proftpd_display_connect: "{{ proftpd_welcome }}"
    base_ssh_host_keys_dir: /etc/proftpd/ssh_host_keys
    proftpd_virtualhosts:
      - id: sftp
        address: 0.0.0.0
        options:
          - Port: "{{ proftpd_sftp_port}}"
          - SFTPEngine: on
          - SFTPPAMEngine: off
          - CreateHome: on dirmode 700
          - SFTPHostKey: "{{ base_ssh_host_keys_dir }}/rsa"
          - SFTPHostKey: "{{ base_ssh_host_keys_dir }}/dsa"
          - SFTPCompression: delayed
          - SQLEngine: on
          - SQLPasswordEngine: on
          - SQLLogFile: /var/log/proftpd/sql.log
          - SQLBackend: postgres
          - SQLAuthenticate: users
          - SQLConnectInfo: "{{ proftpd_sql_db }} {{ proftpd_sql_user }} {{ proftpd_sql_password }}"
          - SQLAuthTypes: PBKDF2 SHA1
          - SQLPasswordPBKDF2: sql:/GetPBKDF2Params
          - SQLPasswordEncoding: base64
          - SQLUserInfo: custom:/LookupGalaxyUser
          - SQLPasswordUserSalt: sql:/GetUserSalt
          - SQLNamedQuery: GetPBKDF2Params  SELECT "(CASE WHEN split_part(password, '$', 1) = 'PBKDF2' THEN UPPER(split_part(password, '$', 2)) ELSE 'SHA256' END), (CASE WHEN split_part(password, '$', 1) = 'PBKDF2' THEN split_part(password, '$', 3) ELSE '10000' END), 24 FROM galaxy_user WHERE email='%U'"
          - SQLNamedQuery: GetUserSalt      SELECT "(CASE WHEN split_part(password, '$', 1) = 'PBKDF2' THEN split_part(password, '$', 4) END) FROM galaxy_user WHERE email='%U'"
          - SQLNamedQuery: LookupGalaxyUser SELECT "email, (CASE WHEN split_part(password, '$', 1) = 'PBKDF2' THEN split_part(password, '$', 5) ELSE encode(decode(password, 'hex'), 'base64') END),'{{ galaxy_user_name }}','{{ galaxy_user_name }}','{{ galaxy_ftp_upload_dir }}/%U','/bin/bash' FROM galaxy_user WHERE email='%U'"

  # Required for sftp server
  pre_tasks:
    - name: Install OpenSSH client package
      apt: pkg=openssh-client

    - name: Create ssh host keys directory
      file: path="{{ base_ssh_host_keys_dir }}" state=directory

    - name: Generate new SSH keys (rsa)
      shell: ssh-keygen -b 2048 -t rsa -f "{{ base_ssh_host_keys_dir }}/rsa" -N ""
      args:
        creates: "{{ base_ssh_host_keys_dir }}/rsa"

    - name: Generate new SSH keys (dsa)
      shell: ssh-keygen -b 1024 -t dsa -f "{{ base_ssh_host_keys_dir }}/dsa" -N ""
      args:
        creates: "{{ base_ssh_host_keys_dir }}/dsa"

  roles:
    - role: galaxyproject.proftpd
