- hosts: localhost
  connection: local
  remote_user: root
  vars:
    slurm_roles: ['controller', 'exec']
    slurm_config:
      SlurmctldHost: localhost
      SlurmUser: '{{ galaxy_user_name }}'
      SelectType: select/cons_tres
      SelectTypeParameters: CR_Core_Memory
      StateSaveLocation: /tmp/slurm
      ReturnToService: 1
  roles:
    - role: galaxyproject.slurm
    # - role: galaxyproject.repos
  tasks:
    # The ppa repository addition task from galaxyproject.repos role is not working
    # after setting "APT::Install-Recommends" to false by default. Hence, added the task manually.
    # FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://ppa.launchpad.net/natefoo/slurm-drmaa/ubuntu sid Release' does not have a Release file."}
    - name: Import the GPG signing key for the PPA
      apt_key:
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8DE68488997C5C6BA19021136F2CC56412788738"
        state: present

    - name: Add PPA repository for Slurm-DRMAA
      apt_repository:
        repo: "deb https://ppa.launchpadcontent.net/natefoo/slurm-drmaa/ubuntu {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install slurm-drmaa package
      package:
        name: slurm-drmaa1
        state: "{{ galaxy_apt_package_state }}"

    - name: Create symbolic link for libdrmaa.so
      file:
        src: /usr/lib/slurm-drmaa/lib/libdrmaa.so.1
        dest: /usr/lib/slurm-drmaa/lib/libdrmaa.so
        state: link

    - name: Setup tmp area for slurm
      file: path=/tmp/slurm state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}

    - name: Add script to update slurm configuration file
      template: src=configure_slurm.py.j2 dest=/usr/sbin/configure_slurm.py mode=0755

    - name: Setup Munge permissions and folder
      file: path={{ item }} state=directory owner=root group=root recurse=yes
      with_items:
        - /var/run/munge
        - /var/lib/munge
        - /var/log/munge
        - /var/run/munge
        - /etc/munge

    # If job_conf.xml is installed before running galaxyprojectdotorg.galaxy, this would already be installed.
    - name: Fetch DRMAA wheel for Galaxy
      pip:
        name: "drmaa"
        extra_args: "--index-url https://wheels.galaxyproject.org/simple/ --extra-index-url https://pypi.python.org/simple"
        virtualenv: "{{ galaxy_venv_dir }}"
      environment:
        PYTHOPATH: null
        VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
      become_user: "{{ galaxy_user_name }}"
