- hosts: localhost
  connection: local
  remote_user: root
  tasks:
    - name: Install supervisor package
      apt: 
        state: "{{ galaxy_apt_package_state }}"
        name: supervisor

    - name: Install cron
      apt: 
        state: "{{ galaxy_apt_package_state }}"
        name: cron
      when: supervisor_manage_cron | bool

    - name: Create Galaxy configuration file
      template: src=supervisor.conf.j2 dest={{ supervisor_conf_path }}

    - name: Stop supervisor
      service: name=supervisor state=stopped

    - name: Stop and remove munge.
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - munge
      when: supervisor_manage_slurm | bool

    - name: Stop and remove slurm.
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - slurmd
        - slurmctld
      when: supervisor_manage_slurm | bool

    - name: Stop and remove postgresql.
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - postgresql
      when: supervisor_manage_postgres | bool 

    - name: Stop and remove proftpd.
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - proftpd
      when: supervisor_manage_proftp | bool

    - name: Stop and remove nginx.
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - nginx
      when: supervisor_manage_nginx | bool

    - name: Stop and remove rabbitmq.
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - rabbitmq-server
      when: supervisor_manage_rabbitmq | bool

    - name: Stop and remove redis.
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - redis-server
      when: supervisor_manage_redis | bool

    - name: Purge systemd and perform cleanup
      shell: apt purge -y systemd && apt-get autoremove -y && apt-get clean

    - name: Start supervisor
      service: name=supervisor state=started
