gravity:
  process_manager: supervisor
  galaxy_root: /galaxy
  virtualenv: /galaxy/.venv
  gunicorn:
    enable: True
    bind: 0.0.0.0:5555
    workers: 2
  celery:
    enable: true
    enable_beat: true
    concurrency: 2
  handlers:
    handler:
      processes: 2
      pools:
        - job-handlers
        - workflow-schedulers

galaxy:
  tool_dependency_dir: /tool_deps
  tool_data_table_config_path: /cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml
  tus_upload_store: /tus_upload_store
  enable_celery_tasks: true
  celery_conf:
    result_backend: redis://redis:6379/0

pulsar:
  conda_auto_init: True
  conda_auto_install: True
  tool_dependency_dir: dependencies
  dependency_resolution:
    resolvers:
      - type: conda
        auto_init: true
        auto_install: true
      - type: conda
        versionless: true

# Probably needs more polishing, but at least it works..
slurm:
  SlurmctldHost: "slurmctld"
  AuthType: "auth/munge"
  CryptoType: "crypto/munge"
  MpiDefault: "none"
  ProctrackType: "proctrack/pgid"
  ReturnToService: "1"
  SlurmctldPidFile: "/var/run/slurmctld.pid"
  SlurmctldPort: "6817"
  SlurmdPidFile: "/var/run/slurmd.pid"
  SlurmdPort: "6818"
  SlurmdSpoolDir: "/tmp/slurmd"
  SlurmUser: "slurm"
  StateSaveLocation: "/tmp/slurm"
  SwitchType: "switch/none"
  TaskPlugin: "task/none"
  InactiveLimit: "0"
  KillWait: "30"
  MinJobAge: "300"
  SlurmctldTimeout: "120"
  SlurmdTimeout: "300"
  Waittime: "0"
  SchedulerType: "sched/backfill"
  SelectType: "select/cons_res"
  SelectTypeParameters: "CR_Core_Memory"
  AccountingStorageType: "accounting_storage/none"
  AccountingStoreFlags: "job_comment"
  ClusterName: "Cluster"
  JobCompType: "jobcomp/none"
  JobAcctGatherFrequency: "30"
  JobAcctGatherType: "jobacct_gather/none"
  SlurmctldDebug: info
  SlurmdDebug: info

htcondor_galaxy:
  CONDOR_HOST: "htcondor-master"
  ALLOW_ADMINISTRATOR: "*"
  ALLOW_OWNER: "*"
  ALLOW_READ: "*"
  ALLOW_WRITE: "*"
  ALLOW_CLIENT: "*"
  ALLOW_DAEMON: "*"
  ALLOW_NEGOTIATOR: "*"
  DAEMON_LIST: "MASTER, SCHEDD"
  UID_DOMAIN: "galaxy"
  DISCARD_SESSION_KEYRING_ON_STARTUP: "False"
  TRUST_UID_DOMAIN: "true"
  SEC_PASSWORD_FILE: "/var/lib/condor/pool_password"
  SEC_DAEMON_AUTHENTICATION: "REQUIRED"
  SEC_DAEMON_INTEGRITY: "REQUIRED"
  SEC_DAEMON_AUTHENTICATION_METHODS: "PASSWORD"
  SEC_NEGOTIATOR_AUTHENTICATION: "REQUIRED"
  SEC_NEGOTIATOR_INTEGRITY: "REQUIRED"
  SEC_NEGOTIATOR_AUTHENTICATION_METHODS: "PASSWORD"
  SEC_CLIENT_AUTHENTICATION_METHODS: "FS, PASSWORD"

htcondor_master:
  BASE_CGROUP: ""
  CONDOR_HOST: "$(FULL_HOSTNAME)"
  DAEMON_LIST: "MASTER, COLLECTOR, NEGOTIATOR, SCHEDD"
  DISCARD_SESSION_KEYRING_ON_STARTUP: "False"
  TRUST_UID_DOMAIN: "True"
  ALLOW_ADMINISTRATOR: "*"
  ALLOW_OWNER: "*"
  ALLOW_READ: "*"
  ALLOW_WRITE: "*"
  ALLOW_NEGOTIATOR: "*"
  ALLOW_NEGOTIATOR_SCHEDD: "*"
  ALLOW_WRITE_COLLECTOR: "*"
  ALLOW_WRITE_STARTD: "*"
  ALLOW_READ_COLLECTOR: "*"
  ALLOW_READ_STARTD: "*"
  ALLOW_CLIENT: "*"
  ALLOW_DAEMON: "*"
  DOCKER_IMAGE_CACHE_SIZE: "20"
  UID_DOMAIN: "galaxy"
  TRUST_UID_DOMAIN: "TRUE"
  SEC_PASSWORD_FILE: "/var/lib/condor/pool_password"
  SEC_DAEMON_AUTHENTICATION: "REQUIRED"
  SEC_DAEMON_INTEGRITY: "REQUIRED"
  SEC_DAEMON_AUTHENTICATION_METHODS: "PASSWORD"
  SEC_NEGOTIATOR_AUTHENTICATION: "REQUIRED"
  SEC_NEGOTIATOR_INTEGRITY: "REQUIRED"
  SEC_NEGOTIATOR_AUTHENTICATION_METHODS: "PASSWORD"
  SEC_CLIENT_AUTHENTICATION_METHODS: "FS, PASSWORD"

htcondor_executor:
  CONDOR_HOST: "htcondor-master"
  DAEMON_LIST: "MASTER, STARTD"
  DISCARD_SESSION_KEYRING_ON_STARTUP: "False"
  TRUST_UID_DOMAIN: "true"
  NUM_SLOTS: "1"
  NUM_SLOTS_TYPE_1: "1"
  BASE_CGROUP: ""
  ALLOW_ADMINISTRATOR: "*"
  ALLOW_OWNER: "*"
  ALLOW_READ: "*"
  ALLOW_WRITE: "*"
  ALLOW_CLIENT: "*"
  ALLOW_DAEMON: "*"
  ALLOW_NEGOTIATOR_SCHEDD: "*"
  ALLOW_WRITE_COLLECTOR: "*"
  ALLOW_WRITE_STARTD: "*"
  ALLOW_READ_COLLECTOR: "*"
  ALLOW_READ_STARTD: "*"
  UID_DOMAIN: "galaxy"
  SCHED_NAME: "htcondor-master"
  SEC_PASSWORD_FILE: "/var/lib/condor/pool_password"
  SEC_DAEMON_AUTHENTICATION: "REQUIRED"
  SEC_DAEMON_INTEGRITY: "REQUIRED"
  SEC_DAEMON_AUTHENTICATION_METHODS: "PASSWORD"
  SEC_NEGOTIATOR_AUTHENTICATION: "REQUIRED"
  SEC_NEGOTIATOR_INTEGRITY: "REQUIRED"
  SEC_NEGOTIATOR_AUTHENTICATION_METHODS: "PASSWORD"
  SEC_CLIENT_AUTHENTICATION_METHODS: "FS, PASSWORD"
